# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1d208f560100090978dd7c7599cc470a28683551de83a33d13f6ba6123a24d14b93e7b0406d5d804f7995256b4a8cafea1d8d48e51359d8e5da78f95a6eb624

test:
  secret_key_base: 4e12196aec98d5ce480e252e72ee6d561b79ab3cdad864dc25cee558965a89332d5aab58021043cfd086ed8802cb39cf6737b718659df39a81166792811098c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
